/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'REE',
      items: [
        'REE/introduction',
        'REE/btcfi-design-guide',
        'REE/first-exchange',
        'REE/next-steps',
        'REE/apis',
        {
          type: 'category',
          label: 'REE Workshop',
          items: [
            'REE/game-demo',
            'REE/define-pool-state',
            'REE/store-pool-data',
            'REE/initialize-a-pool',
            'REE/implement-ree-exchange-methods',
            'REE/implement-the-game-functions',
            'REE/implement-the-frontend',
            'REE/next-steps-and-resources',
          ],
          collapsed: false,
        },
      ],
    },
    {
      type: 'category',
      label: 'RichSwap',
      items: [
        'Rich-Swap/guide',
        'Rich-Swap/apis',
      ],
    },
    {
      type: 'category',
      label: 'OmnityHub',
      items: [
        'Omnity-Hub/intro',
        'Omnity-Hub/evm',
        'Omnity-Hub/runes_indexer',
        'Omnity-Hub/runes',
        'Omnity-Hub/icp_icrc',
        'Omnity-Hub/cosmwasm',
        'Omnity-Hub/solana_settlement',
        'Omnity-Hub/solana_execution',
        'Omnity-Hub/dogecoin',
        'Omnity-Hub/ton',
        'Omnity-Hub/explorer',
        'Omnity-Hub/faq',
        'Omnity-Hub/references',
      ],
    },
  ],
};

module.exports = sidebars;
