/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'REE',
      items: [
        'REE/introduction',
        'REE/core-concepts',
        'REE/first-exchange',
        'REE/state-management',
        'REE/next-steps',
        'REE/apis',

      ],
    },
    {
      type: 'category',
      label: 'Rich-Swap',
      items: [
        'Rich-Swap/apis',
        'Rich-Swap/guide',
      ],
    },
    {
      type: 'category',
      label: 'Omnity-Hub',
      items: [
        'Omnity-Hub/intro',
        'Omnity-Hub/evm',
        'Omnity-Hub/runes_indexer',
        'Omnity-Hub/runes',
        'Omnity-Hub/icp_icrc',
        'Omnity-Hub/cosmwasm',
        'Omnity-Hub/solana_settlement',
        'Omnity-Hub/solana_execution',
        'Omnity-Hub/dogecoin',
        'Omnity-Hub/ton',
        'Omnity-Hub/explorer',
        'Omnity-Hub/faq',
        'Omnity-Hub/references',
      ],
    },
  ],
};

module.exports = sidebars;
